DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Items;

CREATE TABLE IF NOT EXISTS
Orders(
  id SERIAL PRIMARY KEY NOT NULL,
  fullName VARCHAR(256) NOT NULL,
  phoneNumber VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL,
  city VARCHAR(256) NOT NULL,
  area VARCHAR(256) NOT NULL,
  count int NOT NULL,
  accepted boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS
Items(
  id SERIAL PRIMARY KEY NOT NULL,
  img VARCHAR(256) NOT NULL,
  title VARCHAR(256) NOT NULL,
  description VARCHAR(256) NOT NULL,
  maxCount int NOT NULL,
  minCount int NOT NULL,
  count int NOT NULL
);