DROP TABLE IF EXISTS Orders;

CREATE TABLE IF NOT EXISTS
Orders(
  id SERIAL PRIMARY KEY NOT NULL,
  fullName VARCHAR(256) NOT NULL,
  phoneNumber VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL,
  city VARCHAR(256) NOT NULL,
  area VARCHAR(256) NOT NULL,
  count int NOT NULL,
  accepted boolean NOT NULL
);
